FROM centos:centos7
RUN yum clean all && \
    yum -y install epel-release && \
    yum -y install PyYAML python-jinja2 python-httplib2 python-keyczar python-paramiko python-setuptools git python-pip
RUN mkdir /etc/ansible/
RUN echo -e '[local]\nlocalhost\n\n[node]\nnode01\nnode02\node03' > /etc/ansible/hosts
RUN pip install ansible
# # set locale
# RUN yum update -y glibc-common && \
#     yum clean all
# ENV LANG ja_JP.UTF-8
# ENV LANGUAGE ja_JP:ja
# ENV LC_ALL ja_JP.UTF-8
# RUN unlink /etc/localtime
# RUN ln -s /usr/share/zoneinfo/Japan /etc/localtime